### ISSUE TITLE
Fails with Webpack 5

### ISSUE THREAD

**Issue by jaschaio** [sun1l/rename-output-webpack-plugin#3]
```
[webpack-cli] TypeError: compiler.plugin is not a function
at renameOutputPlugin.apply (/app/node_modules/rename-output-webpack-plugin/dist/index.js:87:22)
at createCompiler (/app/node_modules/webpack/lib/webpack.js:69:12)
at create (/app/node_modules/webpack/lib/webpack.js:113:15)
at webpack (/app/node_modules/webpack/lib/webpack.js:121:46)
at f (/app/node_modules/webpack/lib/index.js:35:15)
at WebpackCLI.createCompiler (/app/node_modules/webpack-cli/lib/webpack-cli.js:176:24)
at WebpackCLI.run (/app/node_modules/webpack-cli/lib/webpack-cli.js:268:25)
at async runCLI (/app/node_modules/webpack-cli/lib/bootstrap.js:59:9)
```

**Comment by leopucci** [comment]
@jaschaio have you found another option? I am having the same problem

**Comment by ChengBenj** [comment]
Same issue here.

Any solution?

**Comment by BenceSzalai** [comment]
I think #2 fixed it at its own time, but the event hooks are failing again with today's WebPack version (tried with v5.96.1).

The solution is quite simple, there are two occurances of `compiler.plugin` in https://github.com/sun1l/rename-output-webpack-plugin/blob/master/lib/index.js. The first one needs to be replaced with `compiler.hooks.compilation.tap` and the second one with `compilation.hooks.afterOptimizeChunks.tap`.
